import type { OxlintConfig } from "oxlint"

import { createMergeConfigFn } from "#/utils.ts"
import type { OptionalMergeConfigFn } from "#/utils.ts"

const baseConfig = {
  categories: {
    correctness: "error",
    nursery: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  options: {
    reportUnusedDisableDirectives: "error",
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: [
        ".release-it.ts",
        "commitlint.config.ts",
        "knip.ts",
        "oxfmt.config.ts",
        "oxlint.config.ts",
        "tsdown.config.ts",
        "vitest.config.ts",
      ],
      rules: {
        "import/no-default-export": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "react",
    "unicorn",
    "typescript",
    "oxc",
    "import",
    "jsdoc",
    "vitest",
    "jsx-a11y",
    "react-perf",
    "promise",
    "node",
  ],
  rules: {
    curly: ["error", "multi-or-nest"],
    "func-style": ["error", "expression"],
    "node/no-sync": ["error", { ignores: ["existsSync", "spawnSync"] }],
    "require-unicode-regexp": ["error", { requireFlag: "v" }],

    "capitalized-comments": "off",
    "id-length": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/no-named-export": "off",
    "import/no-nodejs-modules": "off",
    "import/prefer-default-export": "off",
    "init-declarations": "off",
    "jsdoc/require-param": "off",
    "jsdoc/require-returns": "off",
    "max-classes-per-file": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-statements": "off",
    "no-console": "off",
    "no-continue": "off",
    "no-duplicate-imports": "off",
    "no-inline-comments": "off",
    "no-magic-numbers": "off",
    "no-plusplus": "off",
    "no-ternary": "off",
    "no-undef": "off",
    "no-undefined": "off",
    "no-useless-return": "off",
    "node/callback-return": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "typescript/consistent-return": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/strict-boolean-expressions": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/switch-case-braces": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/prefer-describe-function-title": "off",
    "vitest/prefer-expect-assertions": "off",
    "vitest/prefer-lowercase-title": "off",
    "vitest/prefer-to-be-falsy": "off",
    "vitest/prefer-to-be-truthy": "off",
    "vitest/require-hook": "off", // reenable when false positives are fixed?
    "vitest/require-test-timeout": "off",
  },
} as const satisfies OxlintConfig

export const oxlintConfig: OptionalMergeConfigFn<OxlintConfig, typeof baseConfig> = createMergeConfigFn(baseConfig)
