name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install lefthook
        run: |
          bun add -g lefthook
          bun pm bin -g >> "$GITHUB_PATH"

      - name: Install
        run: bun install

      - name: Build + lint
        run: just build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || github.token }}

      - name: Lint last commit message
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose

      - name: Lint PR commit messages
        if: github.event_name == 'pull_request'
        run: bun commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
