name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: adamhl8/configs/.github/actions/setup@main

      - name: Build + lint
        run: just build
        env:
          # some projects require a github token with more permissions than the default repo scoped one
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || github.token }}

      - name: Lint last commit message
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose

      - name: Lint PR commit messages
        if: github.event_name == 'pull_request'
        run: bun commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
