name: Update dependencies

on:
  schedule:
    - cron: "0 13 * * 5" # Fridays, 13:00 UTC
  workflow_dispatch: {}
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install lefthook
        run: |
          bun add -g lefthook
          bun pm bin -g >> "$GITHUB_PATH"

      - name: Install
        run: bun install --ignore-scripts

      - name: Update dependencies
        run: just bump-deps

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        env:
          LEFTHOOK: "0"
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: chore/update-deps
          delete-branch: true
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: ""
